spring.datasource.url=jdbc:mysql://localhost:3306/workstudy
spring.datasource.username=root
spring.datasource.password=Satwik@2006august

spring.jpa.hibernate.ddl-auto=update

# Gmail SMTP Authentication Configuration (MFA)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# REPLACE THIS with the actual Gmail address you just logged into:
spring.mail.username=kuppilisatwik@gmail.com
spring.mail.password=utgzeilbjcwbnwbtw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.jpa.show-sql=true

server.port=8080

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
